baseURL: 'https://tech-memo.meijin.dev/'
languageCode: 'ja-JP'
title: Meijin's Tech Tips
theme: "PaperMod"
googleAnalytics: UA-143780066-1

params:
    description: "名人が技術に関するちょっとしたTipsを書き留めているWebページです / A web page where Meijin writes down little tips about technology."
    homeInfoParams:
      Title: Meijin's Tech Tips
      Content: 名人が日々の技術に関するちょっとしたTipsを集約しているWebページです
    socialIcons:
        - name: twitter
          url: "https://twitter.com/meijin_garden"
        - name: github
          url: "https://github.com/TeXmeijin"
        - name: zenn
          url: https://zenn.dev/meijin
    defaultTheme: dark
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true

    images:
      - site-feature-image.png
    assets:
      favicon: "/favicon.png"

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: portfolio
      name: Portfolio
      url: https://meijin.dev
      weight: 30
